name: python-ml
dependencies:
  # Basic dependencies
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pandas
  - pillow
  - graphviz
  - python-graphviz

  # Auxiliary tools
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
